/*
* generated by Xtext
*/
package edu.kit.scc.cfeditor.cfengine.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CfengineEditorAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("edu/kit/scc/cfeditor/cfengine/parser/antlr/internal/InternalCfengineEditor.tokens");
	}
}
