/*
 * generated by Xtext
 */
package edu.kit.scc.cfeditor.cfengine;

import edu.kit.scc.cfeditor.cfengine.parser.conversion.CfengineEditorTerminalConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 * 
 * @author Andreas Bender
 * 
 */
public class CfengineEditorRuntimeModule extends AbstractCfengineEditorRuntimeModule {

	/**
	 * Binds the customized value converter.
	 */
	@Override
	public Class<? extends org.eclipse.xtext.conversion.IValueConverterService> bindIValueConverterService() {
		return CfengineEditorTerminalConverters.class;
	}

}
