/*
 * generated by Xtext
 */
package edu.kit.scc.cfeditor.cfengine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.wizard.IProjectCreator;

import edu.kit.scc.cfeditor.cfengine.ui.highlighting.CfengineEditorHighlightingCalculator;
import edu.kit.scc.cfeditor.cfengine.ui.highlighting.CfengineEditorHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 * 
 * @author Andreas Bender
 * 
 */
public class CfengineEditorUiModule extends AbstractCfengineEditorUiModule {

	/**
	 * Constructor for the ui module.
	 * 
	 * @param plugin
	 */
	public CfengineEditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	/**
	 * Binds the semantic highlighting calculator class.
	 * 
	 * @return the highlighting calculator class
	 */
	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return CfengineEditorHighlightingCalculator.class;
	}

	/**
	 * Binds the highlighting configuration class.
	 * 
	 * @return the highlighting configuration class
	 */
	public Class<? extends IHighlightingConfiguration> bindSemanticConfig() {
		return CfengineEditorHighlightingConfiguration.class;
	}

	/**
	 * Declares the new CfengineEditor project creator class.
	 */
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return edu.kit.scc.cfeditor.cfengine.ui.wizard.CfengineEditorNewProjectCreator.class;
	}

}
