/*
 * generated by Xtext
 */
package edu.kit.scc.cfeditor.cfengine.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class CfengineEditorLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public CfengineEditorLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	/*
	 * //Labels and icons can be computed like this:
	 * 
	 * String text(MyModel ele) { return "my "+ele.getName(); }
	 * 
	 * String image(MyModel ele) { return "MyModel.gif"; }
	 */

	// public String image(BodyComponent ele){return "cffile.gif";}
	// public String image(Bundle ele){return "cffile.gif";}
}
