/*
 * generated by Xtext
 */
package edu.kit.scc.cfeditor.cfengine.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CfengineEditorTransformer extends AbstractDeclarativeSemanticModelTransformer {

}
